
; [key context] ; key = booga ; the registry key   context = Dir | DirBg | DeskBg | File | Folder | *
; ext = bmp  -  only if context is File
; menu = menu text
; command = treex -c $target

; ExplorerContext
; Dir => Right click in explorer with a directory selected.
; DirBg => Right click in explorer right pane with nothing selected (background).
; DeskBg => Right click in windows desktop with nothing selected (background).
; File => Right click in explorer with a file selected.
; Folder => ?? Seems to appear for any directory selection. Probably meant for system use.


; * => Seems to be default if not specified in any other section.


[Dir treex]
menu = Treex in directory
command = treex -c $target

[DirBg treex]
menu = Treex in here
command = treex -c $target

[Dir openst]
menu = Open directory with Sublime Text
command = %ProgramFiles%\Sublime Text\subl -c --launch-or-new-window $target

[DirBg openst]
menu = Open here with Sublime Text
command = %ProgramFiles%\Sublime Text\subl -c --launch-or-new-window $target

[Dir findev]
menu = Open directory with Everything
command = %ProgramFiles%\Everything\everything -parent $target

[DirBg findev]
menu = Open here with Everything
command = %ProgramFiles%\Everything\everything -parent $target

[File bat cmd]
menu = Execute
command = cmd /C $target

[File ps1]
menu = Execute PS script
command = powershell -executionpolicy bypass -File $target

[File lua]
menu = Execute lua script
command = lua $target

[File py]
menu = Execute python file
command = py $target

; default is just try to open - shell may or may not be able to
[File *]
menu = Open
command = cmd /C $target  
