
; Default shellinator config file - minimal.
;
; Sections:
; [Dir key] => Right click in explorer with a directory selected. key is the registry key
; [DirBg key] => Right click in explorer right pane with nothing selected (background). key is the registry key
; [DeskBg key] => Right click in windows desktop with nothing selected (background). key is the registry key
; menu = text to show in the context menu
; exec = cmd line to execute where $target is the selected item, builtin env vars like %ProgramFiles% are also supported.
;
; [Run ext1 ext2 ...] => Right click in explorer with a file selected. extN is file extension(s) this applies to.
; exec = cmd line as above

[Dir demo]
menu = Do something with this dir!
exec = start, cmd, /c, "echo Dir demo $target on %COMPUTERNAME% && pause"

[DirBg demo]
menu = Do something with nothing selected!
exec = start, cmd, /c, "echo DirBg demo $target on %COMPUTERNAME% && pause"

[DeskBg demo]
menu = Do something with background!
exec = start, cmd, /c, "echo DeskBg demo $target on %COMPUTERNAME% && pause"

[Run bat cmd]
exec = cmd, /c, $target

[Run ps1]
exec = powershell, -executionpolicy bypass, -File $target

; Default if not handled above.
[Run *]
exec = cmd, /c, $target  
